### ISSUE TITLE
想问句，哥们为什么不用ButterKnife呢

### ISSUE THREAD

**Issue by yeyueduxing** [boredream/BorePlugin#19]
看效果和ButterKnife差不多啊

**Comment by boredream** [comment]
其实都是为了减少findViewById的枯燥代码浪费的时间
ButterKnife是手动写，可以写的少点
我这个是做成自动生成，既然是自动生成。。。那生成多少就无所谓啦，而且原生的无反射又便于理解无学习成本

**Comment by longtaoge** [comment]
[珍惜生命 远离 Butter Knife](http://blog.csdn.net/github_14899071/article/details/51427689)

**Comment by yeyueduxing** [comment]
ButterKnife的项目打包成JAR包或者依赖库，的确是有问题。但正常使用还是非常好的
